name: Dependabot auto-merge

on:
  workflow_call:

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    name: Dependabot auto-merge
    runs-on: ubuntu-latest
    if: >
      (github.event_name == 'pull_request' || github.event_name == 'pull_request_target') &&
      github.event.pull_request.user.login == 'dependabot[bot]' &&
      !github.event.pull_request.draft
    steps:
      - name: Fetch Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@25dd0e34f4fe68f24cc83900b1fe3fe149efef98 # v3.1.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Merge patch, minor, and pre-commit updates
        if: >
          steps.metadata.outputs.update-type == 'version-update:semver-patch' ||
          steps.metadata.outputs.update-type == 'version-update:semver-minor' ||
          steps.metadata.outputs.update-type == 'security-update:semver-patch' ||
          steps.metadata.outputs.update-type == 'security-update:semver-minor' ||
          steps.metadata.outputs.package-ecosystem == 'pre_commit'
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
